apiVersion: v1
kind: Service
metadata:
  name:frontend-service
  labels:
    app: portfolio
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: portfolio
    tier: frontend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80

